language: node_js
node_js:
  - 12.1
before_deploy:
  - yarn build
deploy:
  provider: pages
  local-dir: build
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
